spring:
  datasource:
    url: jdbc:mysql://******
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    enabled: false
code:
  schema: presell
  pojoPkg: test
  mapperPkg: test
  tableName: presell_stock
  pojoName: test
  mapperName: test
  typesMap:
    Long-INTEGER: BIGINT,INT,INTEGER
    java.math.BigDecimal-DECIMAL: DOUBLE,FLOAT,DECIMAL,NUMERIC
    String-VARCHAR: VARCHAR,NVARCHAR,LONGTEXT,TEXT
logging:
  level:
    root: error


