spring:
  datasource:
#    url: jdbc:mysql://common101.my.2dfire-daily.com:3306/presell_guard?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true
#    username: presell_guard
#    password: presell_guard@552208
    url: jdbc:mysql://common101.my.2dfire-daily.com:3306/presell_market?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true
    username: twodfire
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    enabled: false
code:
  schema: presell_market
  mapperPkg: com.dfire.soa.cm.internal.dao
  pojoPkg: com.dfire.soa.cm.internal.domain
  tableName: presell_activity,cut_price_record,cut_price_join
  typesMap:
    Long-Long: BIGINT,INTEGER
    Integer-TINYINT: TINYINT,INT
    java.math.BigDecimal-DECIMAL: DOUBLE,FLOAT,DECIMAL,NUMERIC
    String-VARCHAR: VARCHAR,NVARCHAR,LONGTEXT,TEXT
logging:
  level:
    root: error
