spring:
  datasource:
    url: jdbc:mysql://common101.my.2dfire-daily.com:3306/presell_guard?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true
    username: presell_guard
    password: presell_guard@552208
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    enabled: false
code:
  schema: presell_guard
  mapperPkg: com.dfire.soa.guard.presell.dao
  pojoPkg: com.dfire.soa.guard.presell.domain
  tableName: user_role,menu,role_menu,user_menu,market_user,role
  typesMap:
    Long-Long: BIGINT,INTEGER
    Integer-TINYINT: TINYINT,INT
    java.math.BigDecimal-DECIMAL: DOUBLE,FLOAT,DECIMAL,NUMERIC
    String-VARCHAR: VARCHAR,NVARCHAR,LONGTEXT,TEXT
logging:
  level:
    root: error
