spring:
  datasource:
    url: jdbc:mysql:******
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    enabled: false
code:
  #数据库名
  schema: test
  #pojo包名
  pojoPkg: test
  #mapper命名空间
  mapperPkg: test
  #表名
  tableName: test
  #模板路径
  path: config
  #类型转换map
  typesMap:
    Long-INTEGER: BIGINT,INT,INTEGER
    java.math.BigDecimal-DECIMAL: DOUBLE,FLOAT,DECIMAL,NUMERIC
    String-VARCHAR: VARCHAR,NVARCHAR,LONGTEXT,TEXT
logging:
  level:
    root: error


